apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Smriti-21306/argocd-private.git //ssh url should be mentioned
    sshPrivateKeySecret:
      name: github-ssh-key-secret
      key: sshPrivateKey
    targetRevision: HEAD
    path: dev
    # path: argo-chart
    # helm:
    #   valueFiles:
    #     - values.yaml
    #     - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
