apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deploymentName}}
  labels:
    app: {{.Values.appName}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{.Values.appName}}
  template:
    metadata:
      labels:
        app: {{.Values.appName}}
    spec:
      containers:
      - name: smriti-docker
        image: {{.Values.imageName}}
        ports:
        - containerPort: 9090