apiVersion: v1
kind: Service
metadata:
  name: {{.Values.serviceName}}
  namespace : {{.Values.namespace}}
spec:
  selector:
    app: {{.Values.appName}}
  type: NodePort
  ports:
  - port: 8110
    nodePort: {{.Values.portNumber}}
    targetPort: 9090